In [1]:
import pandas as pd

In [25]:
df = pd.read_csv("../ety_data.csv")

C:\Users\conjunct\AppData\Local\Temp\ipykernel_19880\3605206515.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../ety_data.csv")

In [26]:
df

,Unnamed: 0,word,lang,ety,templates,etymology_number,subpart
0,0,abaft,English,"From a- (“on”) + Middle English baft, baften, ...","[{'name': 'm', 'args': {'1': 'en', '2': 'a-', ...",0,10
1,1,abaft,English,"From a- (“on”) + Middle English baft, baften, ...","[{'name': 'm', 'args': {'1': 'en', '2': 'a-', ...",0,10
2,2,abraid,English,"From Middle English abraiden, abreiden (“to st...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",1,10
3,3,abear,English,"From Middle English aberen, from Old English ā...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",0,10
4,4,abear,English,"From Middle English aberen, from Old English ā...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",0,10
...,...,...,...,...,...,...,...
915346,915346,iš,Lithuanian,"From Proto-Indo-European *eḱs (“out of”), *eǵʰ...","[{'name': 'der', 'args': {'1': 'lt', '2': 'ine...",0,9
915347,915347,stafróf,Icelandic,"From Old Norse stafróf, from Old English stæfr...","[{'name': 'der', 'args': {'1': 'is', '2': 'non...",0,9
915348,915348,fló,Old Norse,"table\nFrom Proto-Germanic *flauhaz, from Prot...","[{'name': 'etymid', 'args': {'1': 'non', '2': ...",2,9
915349,915349,échauffer,French,"Inherited from Middle French eschauffer, from ...","[{'name': 'glossary', 'args': {'1': 'Inherited...",0,9
915350,915350,bucca,Old English,"From Proto-West Germanic *bukkō, from Proto-Ge...","[{'name': 'inh', 'args': {'1': 'ang', '2': 'gm...",0,9

In [27]:
# if df's subpart is 2_x, then create a new column called split with the value of x
df["split"] = df["subpart"].str.extract(r"[23]_(\d+)")

# change NaN to -1
df["split"] = df["split"].fillna(-1)

# then change subpart of any column that matches (2|3)_\d+ to 2 or 3
df["subpart"] = df["subpart"].str.extract(r"(\d+)_?\d*") # .fillna(df["subpart"])

In [28]:
df

,Unnamed: 0,word,lang,ety,templates,etymology_number,subpart,split
0,0,abaft,English,"From a- (“on”) + Middle English baft, baften, ...","[{'name': 'm', 'args': {'1': 'en', '2': 'a-', ...",0,10,-1
1,1,abaft,English,"From a- (“on”) + Middle English baft, baften, ...","[{'name': 'm', 'args': {'1': 'en', '2': 'a-', ...",0,10,-1
2,2,abraid,English,"From Middle English abraiden, abreiden (“to st...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",1,10,-1
3,3,abear,English,"From Middle English aberen, from Old English ā...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",0,10,-1
4,4,abear,English,"From Middle English aberen, from Old English ā...","[{'name': 'inh', 'args': {'1': 'en', '2': 'enm...",0,10,-1
...,...,...,...,...,...,...,...,...
915346,915346,iš,Lithuanian,"From Proto-Indo-European *eḱs (“out of”), *eǵʰ...","[{'name': 'der', 'args': {'1': 'lt', '2': 'ine...",0,NaN,-1
915347,915347,stafróf,Icelandic,"From Old Norse stafróf, from Old English stæfr...","[{'name': 'der', 'args': {'1': 'is', '2': 'non...",0,NaN,-1
915348,915348,fló,Old Norse,"table\nFrom Proto-Germanic *flauhaz, from Prot...","[{'name': 'etymid', 'args': {'1': 'non', '2': ...",2,NaN,-1
915349,915349,échauffer,French,"Inherited from Middle French eschauffer, from ...","[{'name': 'glossary', 'args': {'1': 'Inherited...",0,NaN,-1
915350,915350,bucca,Old English,"From Proto-West Germanic *bukkō, from Proto-Ge...","[{'name': 'inh', 'args': {'1': 'ang', '2': 'gm...",0,NaN,-1